#!/bin/bash
#
# Installs the cron job that runs backup.sh.
#
# Important: cron does NOT inherit the environment of the process that starts
# it, so variables passed to the container with `-e` would be invisible to the
# job. This script therefore serializes them into $BACKUP_ENV_FILE (mode 0600)
# and the job reloads them with `.` before launching backup.sh.
#
set -euo pipefail

CRON_SCHEDULE="${CRON_SCHEDULE:-0 2 * * *}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_SCRIPT="${BACKUP_SCRIPT:-$SCRIPT_DIR/backup.sh}"
BACKUP_ENV_FILE="${BACKUP_ENV_FILE:-$SCRIPT_DIR/backup.env}"
# cron detaches the job from any terminal, so its output must be redirected
# explicitly. /proc/1/fd/1 is PID 1's stdout: inside the container that is the
# console collected by `docker logs`, so nothing is written to the filesystem.
CRON_LOG="${CRON_LOG:-/proc/1/fd/1}"
RUN_ON_START="${RUN_ON_START:-false}"
CRON_MARKER="# managed-by:postgresqldump"

log() { printf '[schedule] %s\n' "$1"; }
die() { printf '[schedule] ERROR: %s\n' "$1" >&2; exit 1; }

# =========================
# VALIDATION
# =========================
command -v crontab >/dev/null 2>&1 || die "'crontab' not available in PATH"
command -v bash >/dev/null 2>&1 || die "'bash' not available in PATH"
[ -f "$BACKUP_SCRIPT" ] || die "backup script not found: $BACKUP_SCRIPT"
[ -r "$BACKUP_SCRIPT" ] || die "backup script not readable: $BACKUP_SCRIPT"

# The crontab command quotes these paths with single quotes.
case "$BACKUP_SCRIPT$BACKUP_ENV_FILE$CRON_LOG" in
  *\'*) die "paths must not contain single quotes" ;;
esac

case "$CRON_SCHEDULE" in
  *$'\n'*|*$'\r'*) die "CRON_SCHEDULE must be a single line" ;;
  *%*)             die "CRON_SCHEDULE cannot contain '%' (special character for cron)" ;;
esac

if [ "${CRON_SCHEDULE:0:1}" = "@" ]; then
  case "$CRON_SCHEDULE" in
    @reboot|@yearly|@annually|@monthly|@weekly|@daily|@midnight|@hourly) : ;;
    *) die "invalid cron shortcut: '$CRON_SCHEDULE'" ;;
  esac
else
  CRON_FIELDS="$(printf '%s' "$CRON_SCHEDULE" | wc -w)"
  [ "$CRON_FIELDS" -eq 5 ] \
    || die "CRON_SCHEDULE must have 5 fields (or be a shortcut such as @daily); got $CRON_FIELDS: '$CRON_SCHEDULE'"
fi

# =========================
# ENVIRONMENT FOR THE JOB
# =========================
PASSTHROUGH_VARS="
PGHOST PGPORT PGUSER PGPASSWORD PGDATABASE PGCONNECT_TIMEOUT PGSSLMODE
S3_BUCKET S3_PREFIX S3_ENDPOINT_URL
AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_DEFAULT_REGION
INTERVAL BACKUP_ROOT LOG_COLOR LOCK_FILE
"

log "Writing cron environment to $BACKUP_ENV_FILE"

# umask is restored right after: leaving it at 077 would also apply to the
# archives written by backup.sh under RUN_ON_START, giving them permissions
# different from those produced by the scheduled runs.
OLD_UMASK="$(umask)"
umask 077
{
  echo "# Generated by schedule.sh - do not edit by hand."
  echo "# cron does not inherit the container environment: these variables are"
  echo "# reloaded by the job before running backup.sh."
  for var in $PASSTHROUGH_VARS; do
    if [ -n "${!var:-}" ]; then
      printf 'export %s=%q\n' "$var" "${!var}"
    fi
  done
} > "$BACKUP_ENV_FILE"
chmod 600 "$BACKUP_ENV_FILE"
umask "$OLD_UMASK"

EXPORTED="$(grep -c '^export ' "$BACKUP_ENV_FILE" || true)"
log "Exported $EXPORTED variables to the cron job"

# =========================
# CRONTAB INSTALLATION
# =========================
CRON_TMP="$(mktemp)"
trap 'rm -f "$CRON_TMP"' EXIT

# Only removes the lines managed by this script; the previous
# `sed /backup.sh/d` deleted any third-party job that mentioned backup.sh.
crontab -l 2>/dev/null | grep -vF "$CRON_MARKER" > "$CRON_TMP" || true

# The env file is written with `printf %q`, i.e. bash quoting, so it must be
# sourced by bash and not by cron's /bin/sh (busybox ash on Alpine): a value
# containing control characters would be emitted as $'...', a bashism.
# `bash -c 'script' arg0 arg1` sets $0/$1, which keeps the paths out of the
# quoted script and avoids a second level of escaping.
{
  echo "$CRON_MARKER"
  echo "$CRON_SCHEDULE bash -c '. \"\$0\" && exec \"\$1\"' '$BACKUP_ENV_FILE' '$BACKUP_SCRIPT' >> '$CRON_LOG' 2>&1 $CRON_MARKER"
} >> "$CRON_TMP"

crontab "$CRON_TMP"

# Explicit check: without it, a failed `crontab` would go unnoticed and the
# container would stay up with no backup scheduled at all.
crontab -l 2>/dev/null | grep -qF "$CRON_MARKER" \
  || die "cron job installation failed: crontab does not contain the job"

log "Cron job installed:"
crontab -l 2>/dev/null | grep -F "$CRON_MARKER" | grep -v '^#' | sed 's/^/[schedule]   /' || true
log "Schedule ......: $CRON_SCHEDULE"
log "Script ........: $BACKUP_SCRIPT"
log "Job output ....: $CRON_LOG"

# =========================
# IMMEDIATE BACKUP (optional)
# =========================
# With RUN_ON_START=true a misconfiguration surfaces right at container start,
# instead of silently at the first scheduled run.
case "${RUN_ON_START,,}" in
  true|1|yes|y|on)
    log "RUN_ON_START enabled: running a verification backup now"
    RC=0
    "$BACKUP_SCRIPT" || RC=$?
    [ "$RC" -eq 0 ] || die "initial backup failed (exit $RC) - check the configuration"
    log "Initial backup completed"
    ;;
  *)
    log "RUN_ON_START disabled: first backup at the next scheduled occurrence"
    ;;
esac
